/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DateRange = IDL.Record({
  'endDate' : IDL.Text,
  'startDate' : IDL.Text,
});
export const Category = IDL.Variant({
  'latestJobs' : IDL.Null,
  'results' : IDL.Null,
  'admitCards' : IDL.Null,
});
export const JobId = IDL.Nat;
export const JobPost = IDL.Record({
  'id' : JobId,
  'fees' : IDL.Text,
  'name' : IDL.Text,
  'links' : IDL.Record({
    'applyOnline' : IDL.Text,
    'notification' : IDL.Text,
    'officialWebsite' : IDL.Text,
  }),
  'syllabusUrl' : IDL.Text,
  'category' : Category,
  'importantDates' : DateRange,
});

export const idlService = IDL.Service({
  'addJobPost' : IDL.Func(
      [
        IDL.Text,
        DateRange,
        IDL.Text,
        Category,
        IDL.Text,
        IDL.Record({
          'applyOnline' : IDL.Text,
          'notification' : IDL.Text,
          'officialWebsite' : IDL.Text,
        }),
      ],
      [JobId],
      [],
    ),
  'getJobPost' : IDL.Func([JobId], [JobPost], ['query']),
  'getJobPostsByCategory' : IDL.Func(
      [IDL.Opt(Category)],
      [IDL.Vec(JobPost)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DateRange = IDL.Record({
    'endDate' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const Category = IDL.Variant({
    'latestJobs' : IDL.Null,
    'results' : IDL.Null,
    'admitCards' : IDL.Null,
  });
  const JobId = IDL.Nat;
  const JobPost = IDL.Record({
    'id' : JobId,
    'fees' : IDL.Text,
    'name' : IDL.Text,
    'links' : IDL.Record({
      'applyOnline' : IDL.Text,
      'notification' : IDL.Text,
      'officialWebsite' : IDL.Text,
    }),
    'syllabusUrl' : IDL.Text,
    'category' : Category,
    'importantDates' : DateRange,
  });
  
  return IDL.Service({
    'addJobPost' : IDL.Func(
        [
          IDL.Text,
          DateRange,
          IDL.Text,
          Category,
          IDL.Text,
          IDL.Record({
            'applyOnline' : IDL.Text,
            'notification' : IDL.Text,
            'officialWebsite' : IDL.Text,
          }),
        ],
        [JobId],
        [],
      ),
    'getJobPost' : IDL.Func([JobId], [JobPost], ['query']),
    'getJobPostsByCategory' : IDL.Func(
        [IDL.Opt(Category)],
        [IDL.Vec(JobPost)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };