/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'latestJobs' : null } |
  { 'results' : null } |
  { 'admitCards' : null };
export interface DateRange { 'endDate' : string, 'startDate' : string }
export type JobId = bigint;
export interface JobPost {
  'id' : JobId,
  'fees' : string,
  'name' : string,
  'links' : {
    'applyOnline' : string,
    'notification' : string,
    'officialWebsite' : string,
  },
  'syllabusUrl' : string,
  'category' : Category,
  'importantDates' : DateRange,
}
export interface _SERVICE {
  'addJobPost' : ActorMethod<
    [
      string,
      DateRange,
      string,
      Category,
      string,
      {
        'applyOnline' : string,
        'notification' : string,
        'officialWebsite' : string,
      },
    ],
    JobId
  >,
  'getJobPost' : ActorMethod<[JobId], JobPost>,
  'getJobPostsByCategory' : ActorMethod<[[] | [Category]], Array<JobPost>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];